### ISSUE TITLE
Job Tracking URL in yarn/MRv2/new API

### ISSUE THREAD

**Issue by onlynone** [spotify/luigi#466]
In [MAPREDUCE-3243](https://issues.apache.org/jira/browse/MAPREDUCE-3243), the tracking URL output was removed from `o.a.h.streaming.StreamJob`. I think this was done for a few reasons:
- From the description in the JIRA: 'The tracking URL for streaming jobs currently display "http://N/A"' (this might be related to the next point)
- In MRv2 they've radically changed the API to the point where there is no JobTracker anymore, some of its responsibilities have been taken over by the new ResourceManager and some by the ApplicationMaster
- The class `o.a.h.mapreduce.Job` already logs the tracking URL in `submit()` as: `LOG.info("The url to track the job: " + getTrackingURL());`

This raises a number of issues for luigi:
- The code in `luigi.hadoop.run_and_track_hadoop_job()` would need to change to grep for "The url to track the job: " in addition to "Tracking URL: "
- For us, the new log message goes to stdout rather than stderr, so the luigi code would need to change to also grep through stdout rather than just stderr
- It appears that the current code will only read one line of stderr at a time while the subprocess is running. If a bunch of lines are printed right before the subprocess exits, several of them could be missed. I think it would make more sense to send both stderr and stdout to a `tempfile.TemporaryFile()` and grep through those files for the interesting strings afterward.
- Even if the tracking URL is found, the code in `luigi.hadoop.fetch_task_failuers()` would need to change in order to handle the new tracking page that's used in hadoop2.0 (I don't think it's specific to yarn, even the new jobhistory server uses a new layout)

It seems like any one of the following changes would have broken this code, it's just that all three are sort of happening at once:
- New web UI layouts (seems to be different between hadoop1.x to hadoop2.x)
- New Map/Reduce api: `org.apache.hadoop.mapred` to `org.apache.hadoop.mapreduce` changing how and where the job tracking URL is logged
- MRv1 (with jobtrackers and tasktrackers) to MRv2/YARN (with resourcemanagers, nodemanagers, and applicationmasters): different services that manage different pieces of data

**Comment by jdangerx** [comment]
I'm running in to this, too. In Hadoop 2.6 I was able to grab the job tracker url from stderr. There's a quick and dirty fix [here](https://github.com/jdangerx/luigi/tree/jobtracker). To grab the logs will take a little more effort - the right thing to do is probably read the hadoop version from config, and go to different URLs based on "apache1" or "apache2".

**Comment by Tarrasch** [comment]
If you find a solution to this and send a PR, we will probably happily merge. :)

**Comment by erikbern** [comment]
Would be awesome if you can fix. This has been bothering me for a while. Should be possible to unit test using the minicluster functionality too

**Comment by jdangerx** [comment]
[This](https://github.com/jdangerx/luigi/tree/jobtracker) also grabs the logs, now, too.  Still needs a test. I'm not sure how to get the minicluster stuff running - I'm getting a connection refused from 50030 when I try to run the Hadoop tests as is. I thought it might have something to do with the fact that the main Hadoop dashboard seems to be at 8088 in Hadoop 2, but changing 50030 to 8088 in `minicluster.py` didn't fix the issue.

**Comment by gpoulin** [comment]
@jdangerx The port 50030 is not the dashboard port but the NameNode port. The easiest way to run the test is probably to change the url [here](https://github.com/spotify/luigi/blob/master/scripts/ci/setup_hadoop_env.sh#L55) with the hadoop version you want to test and run the test with

```bash
tox -e hdp
```

I'm using hadoop 2.6 and the minicluster is running without issue.

**Comment by jdangerx** [comment]
Awesome, thanks!

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
